spring:
  datasource:
    username: root
    password: RoringTec.2
    url: jdbc:mysql://101.43.83.64:3306/mall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 101.43.83.64:8848
  application:
    name: mall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 101.43.83.64
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      use-key-prefix: true
      cache-null-values: true


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0 # 全局逻辑删除规则
server:
  port: 10000
logging:
  level:
    ustc.sse.yyx.product: info

